name: ObjectiveECoS
description: A library to control a ECoS in an objectively friendly way.
version: 1.0.0

repository: https://github.com/TheKingDave/ObjectiveECoS
issue_tracker: https://github.com/TheKingDave/ObjectiveECoS/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ecos_communicator: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
